FROM oven/bun:1

WORKDIR /user/src/app

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

COPY ./apps/websocket/package.json ./apps/websocket/package.json
RUN bun install
COPY ./apps/websocket ./apps/websocket

RUN bun run db:generate

EXPOSE 8081
CMD ["bun","run","start:websocket"]