FROM oven/bun:1

WORKDIR /user/src/app

ARG DATABASE_URL

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

COPY ./apps/web/package.json ./apps/web/package.json

RUN bun install
COPY ./apps/web ./apps/web

RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000
CMD ["bun","run","start:web"]