FROM --platform=linux/amd64 oven/bun

WORKDIR /user/src/app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

COPY ./apps/web/package.json ./apps/web/package.json

RUN bun install
COPY ./apps/web ./apps/web

RUN bun run db:generate
RUN echo "DATABASE_URL is set to: $DATABASE_URL"
RUN bun run build

EXPOSE 3000
CMD ["bun","run","start:web"]